ARG REPO=mcr.microsoft.com/dotnet/aspnet
# Installer image
FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22-arm64v8 as installer
RUN apk update && apk upgrade && apk add --no-cache clang build-base zlib-dev curl


# Trigger first run experience by running arbitrary cmd
RUN dotnet help
