# Build-Stage
FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/nightly/sdk:10.0-preview-alpine3.22-aot-arm64v8 as build
WORKDIR /app

RUN apk add clang build-base zlib-dev
RUN dotnet --version

# Copy the project
COPY example/src/*.csproj ./
RUN dotnet restore

# Copy rest of the code
COPY example/src/. ./
RUN dotnet publish --runtime linux-musl-arm64 --self-contained true -c Release  -o /app/publish
