name: Build AOT for linux-musl-arm64




on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
#    - name: Set up QEMU
#      uses: docker/setup-qemu-action@v3
    
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3        
#    - name: dfd
 #     run: |
#       docker buildx build --platform linux/arm64 -f Dockerfile.aot -t myaddond --load .
    - name: asdfasd
      run: |
          dotnet publish --runtime linux-musl-arm64 --self-contained true -c Release example/srce/MyAddon.csproj
    - name: Zip for Release
      run: |
        sudo zip -r MyAddon.zip ${{ github.workspace }}/example/src/bin/Release/net9.0/linux-musl-arm64/publish/
        #sudo mv ${{ github.workspace }}/example/src/bin/Release/net9.0/linux-musl-x64/MyAddon.zip  ${{github.workspace}}
    - name: Delete latest release and cleanup tag
      run: gh release delete latest --cleanup-tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Create release
      run: gh release create latest --title "Latest Release" ${{github.workspace}}/MyAddon.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
