# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore \example\src\MyAddon.csproj
    - name: Build
      run: dotnet build \example\src\MyAddon.csproj --no-restore
    - name: Publish application
      run: dotnet publish \example\src\MyAddon.csproj --no-build -c Release -r linux-arm64 --self-contained true -p:AssemblyName=MyAddon -o /out
    - name: Zip for Release
      run: Compress-Archive -Path ${{github.workspace}}/out/publish* -Destination ${{github.workspace}}\MyAddon.zip
    - name: Delete latest release and cleanup tag
      run: gh release delete latest --cleanup-tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Create release
      run: gh release create latest --title "Latest Release" ${{github.workspace}}\MyAddon.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
