# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Publish application
      run: dotnet publish example/src/MyAddon.csproj -c Release -r linux-musl-arm64 --self-contained true -p:PublishTrimmed=true
    - name: Zip for Release
      run: |
        cd example/src/bin/Release/net9.0/linux-arm64/publish
        zip -r MyAddon.zip ./*
        mv MyAddon.zip  ${{github.workspace}}
    - name: Delete latest release and cleanup tag
      run: gh release delete latest --cleanup-tag
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Create release
      run: gh release create latest --title "Latest Release" ${{github.workspace}}/MyAddon.zip
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
