name: Build AOT for linux-musl-arm64




on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Build in Docker



      run: |
        docker build -t my-dotnet-aot -f Dockerfile.aot .














    - name: Export AOT artifact










      run: |
        docker run --rm -v ${{ github.workspace }}:/out my-dotnet-aot /w out \
        cp -r /src/bin/Release/net9.0/linux-musl-arm64/native /out/artifact
