name: Build AOT for linux-musl-arm64




on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: dfd
      run: |
       docker build --pull -t myaddond -f Dockerfile.aot 'https://github.com/MartinMGraf/csharp-add1on12111x.git'
    - name: Export AOT artifact
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          -w /src/example/src \
          myaddond \
          dotnet publish --runtime linux-musl-amd64 --self-contained -c Release -o /src/publish MyAddon.csproj
